CREATE TABLE milestone_checklists (id UUID PRIMARY KEY, tenant_id UUID NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, metadata_json JSONB, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE task_assignments (id UUID PRIMARY KEY, tenant_id UUID NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, metadata_json JSONB, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE completion_signals (id UUID PRIMARY KEY, tenant_id UUID NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, metadata_json JSONB, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE escalations (id UUID PRIMARY KEY, tenant_id UUID NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, metadata_json JSONB, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE experience_scores (id UUID PRIMARY KEY, tenant_id UUID NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL, metadata_json JSONB, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL);
ALTER TABLE onboarding_plans ADD COLUMN IF NOT EXISTS name VARCHAR(180) DEFAULT 'Default Name';
ALTER TABLE onboarding_plans ADD COLUMN IF NOT EXISTS metadata_json JSONB;
ALTER TABLE onboarding_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
