package com.microsaas.taxoptimizer.service;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.microsaas.taxoptimizer.domain.entity.AccountantCollaboration;
import com.microsaas.taxoptimizer.domain.entity.TaxProfile;
import com.microsaas.taxoptimizer.domain.repository.AccountantCollaborationRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.ZonedDateTime;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class AccountantIntegrationService {

    private final AccountantCollaborationRepository collaborationRepository;

    public AccountantCollaboration inviteAccountant(UUID tenantId, TaxProfile profile, String email) {
        AccountantCollaboration collab = AccountantCollaboration.builder()
                .tenantId(tenantId)
                .profile(profile)
                .accountantEmail(email)
                .status("PENDING")
                .expiresAt(ZonedDateTime.now().plusMonths(12)) // Archive after 12 months per constraint
                .build();
        return collaborationRepository.save(collab);
    }

    public byte[] generateTaxPackagePdf(TaxProfile profile) throws Exception {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, out);
        document.open();
        document.add(new Paragraph("Tax Organizer Package for " + profile.getFilingStatus()));
        document.add(new Paragraph("Generated by TaxOptimizer"));
        document.add(new Paragraph("State of Residence: " + profile.getStateResidence()));
        document.close();
        return out.toByteArray();
    }
}
