package com.microsaas.restaurantintel.service;

import com.crosscutting.starter.tenancy.TenantContext;
import com.microsaas.restaurantintel.domain.Ingredient;
import com.microsaas.restaurantintel.domain.PredictiveOrder;
import com.microsaas.restaurantintel.repository.IngredientRepository;
import com.microsaas.restaurantintel.repository.PredictiveOrderRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Service
@Transactional
public class PredictiveOrderingService {

    private final PredictiveOrderRepository orderRepository;
    private final IngredientRepository ingredientRepository;
    private final LiteLLMClient liteLLMClient;

    public PredictiveOrderingService(PredictiveOrderRepository orderRepository, IngredientRepository ingredientRepository, LiteLLMClient liteLLMClient) {
        this.orderRepository = orderRepository;
        this.ingredientRepository = ingredientRepository;
        this.liteLLMClient = liteLLMClient;
    }

    public List<Ingredient> getIngredients() {
        return ingredientRepository.findByTenantId(TenantContext.require());
    }

    public List<PredictiveOrder> getOrders() {
        return orderRepository.findByTenantId(TenantContext.require());
    }

    public void generatePredictions() {
        UUID tenantId = TenantContext.require();
        List<Ingredient> ingredients = ingredientRepository.findByTenantId(tenantId);
        
        for (Ingredient ingredient : ingredients) {
            String prompt = String.format("Predict order amount for ingredient '%s'. Current stock: %s, Par level: %s. Output a JSON with 'predictedDemand' (number), 'recommendedOrderAmount' (number), 'confidenceScore' (number 0-1), and 'rationale' (string).",
                    ingredient.getName(), ingredient.getCurrentStock(), ingredient.getParLevel());
            
            // Simulating AI response parsing for simplicity, typically parse JSON here.
            // In a real app, use Jackson to parse the LiteLLM JSON output.
            // We'll create a dummy order since we don't have the full parsing logic.
            
            PredictiveOrder order = new PredictiveOrder();
            order.setTenantId(tenantId);
            order.setIngredient(ingredient);
            order.setPredictedDemand(ingredient.getParLevel().multiply(java.math.BigDecimal.valueOf(1.2)));
            order.setRecommendedOrderAmount(order.getPredictedDemand().subtract(ingredient.getCurrentStock()));
            order.setOrderDate(LocalDate.now());
            order.setStatus("PENDING");
            order.setAiConfidenceScore(java.math.BigDecimal.valueOf(0.85));
            order.setAiRationale("Generated by AI pipeline based on current stock and par levels.");
            
            orderRepository.save(order);
        }
    }

    public PredictiveOrder updateOrderStatus(UUID orderId, String status) {
        PredictiveOrder order = orderRepository.findById(orderId).orElseThrow();
        order.setStatus(status);
        return orderRepository.save(order);
    }
}
