version: '3.8'

services:
  dataqualityai-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8158:8158"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/microsaas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

  dataqualityai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8158

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microsaas
    ports:
      - "5432:5432"
