package com.microsaas.healthcaredocai.service;

import com.microsaas.healthcaredocai.domain.ClinicalEncounter;
import com.microsaas.healthcaredocai.domain.ClinicalTemplate;
import com.microsaas.healthcaredocai.domain.GeneratedNote;
import com.microsaas.healthcaredocai.domain.NoteStatus;
import com.microsaas.healthcaredocai.domain.NoteType;
import com.microsaas.healthcaredocai.repository.ClinicalEncounterRepository;
import com.microsaas.healthcaredocai.repository.ClinicalTemplateRepository;
import com.microsaas.healthcaredocai.repository.GeneratedNoteRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;
import java.util.Optional;

@Service
public class NoteGenerationService {

    private final GeneratedNoteRepository noteRepository;
    private final ClinicalEncounterRepository encounterRepository;
    private final ClinicalTemplateRepository templateRepository;

    public NoteGenerationService(GeneratedNoteRepository noteRepository,
                                 ClinicalEncounterRepository encounterRepository,
                                 ClinicalTemplateRepository templateRepository) {
        this.noteRepository = noteRepository;
        this.encounterRepository = encounterRepository;
        this.templateRepository = templateRepository;
    }

    @Transactional
    public GeneratedNote generateNote(UUID tenantId, UUID encounterId, NoteType noteType, String specialty) {
        ClinicalEncounter encounter = encounterRepository.findByIdAndTenantId(encounterId, tenantId)
                .orElseThrow(() -> new IllegalArgumentException("Encounter not found"));

        Optional<ClinicalTemplate> templateOpt = templateRepository.findByTenantIdAndSpecialtyAndNoteType(tenantId, specialty, noteType);

        String templateFormat = templateOpt.map(ClinicalTemplate::getTemplateFormat).orElse("Default format:\nS:\nO:\nA:\nP:\n");

        // Anthropic Claude API integration goes here to generate note content based on transcript and template
        // Using string interpolation for simulated AI results
        String generatedContent = "Generated by Claude for " + noteType.name() + " in " + specialty + ":\n\nS: " + encounter.getTranscript() + "\nO: Erythematous tonsils without exudate.\nA: Acute pharyngitis.\nP: Symptomatic treatment, warm salt water gargles. Follow-up in 1 week.";

        GeneratedNote note = new GeneratedNote();
        note.setTenantId(tenantId);
        note.setEncounterId(encounterId);
        note.setNoteType(noteType);
        note.setContent(generatedContent);
        note.setStatus(NoteStatus.DRAFT);

        return noteRepository.save(note);
    }
}
