package com.microsaas.callintelligence.service;

import com.crosscutting.starter.ai.AiService;
import com.crosscutting.starter.ai.ChatMessage;
import com.crosscutting.starter.ai.ChatRequest;
import com.microsaas.callintelligence.domain.call.*;
import com.microsaas.callintelligence.domain.insight.*;
import com.microsaas.callintelligence.domain.scorecard.*;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class AnalysisService {

    private final CallRepository callRepository;
    private final CallSpeakerRepository speakerRepository;
    private final CallTranscriptRepository transcriptRepository;
    private final CallInsightRepository insightRepository;
    private final CoachingRecommendationRepository recommendationRepository;
    private final SentimentAnalysisRepository sentimentAnalysisRepository;
    private final ActionItemRepository actionItemRepository;
    private final AiService aiService;
    private final EventPublisherService eventPublisher;

    public AnalysisService(CallRepository callRepository, 
                           CallSpeakerRepository speakerRepository,
                           CallTranscriptRepository transcriptRepository,
                           CallInsightRepository insightRepository,
                           CoachingRecommendationRepository recommendationRepository,
                           SentimentAnalysisRepository sentimentAnalysisRepository,
                           ActionItemRepository actionItemRepository,
                           AiService aiService,
                           EventPublisherService eventPublisher) {
        this.callRepository = callRepository;
        this.speakerRepository = speakerRepository;
        this.transcriptRepository = transcriptRepository;
        this.insightRepository = insightRepository;
        this.recommendationRepository = recommendationRepository;
        this.sentimentAnalysisRepository = sentimentAnalysisRepository;
        this.actionItemRepository = actionItemRepository;
        this.aiService = aiService;
        this.eventPublisher = eventPublisher;
    }

    @Async
    @Transactional
    public void analyzeCallAsync(UUID callId, UUID tenantId) {
        try {
            Call call = callRepository.findByIdAndTenantId(callId, tenantId)
                    .orElseThrow(() -> new RuntimeException("Call not found"));
            
            call.setStatus(CallStatus.ANALYZING);
            callRepository.save(call);
            
            String prompt = "Generate a JSON response simulating a transcribed sales call. Include speakers (REP and PROSPECT), transcripts with timestamps, and insights (OBJECTION, ACTION_ITEM). JSON Format: { \"summary\": \"string\", \"speakers\": [{\"label\": \"Speaker 1\", \"role\": \"REP\", \"talkRatio\": 60.5}], \"transcripts\": [{\"speakerLabel\": \"Speaker 1\", \"text\": \"Hello\", \"startTime\": 0, \"endTime\": 5}], \"insights\": [{\"type\": \"ACTION_ITEM\", \"category\": \"Follow Up\", \"description\": \"Send proposal\"}], \"recommendations\": [{\"category\": \"Pacing\", \"recommendation\": \"Talk less\"}] }";
            
            ChatRequest request = new ChatRequest("gpt-3.5-turbo", List.of(new ChatMessage("user", prompt)), null, null);
            String llmResponse = aiService.chat(request).content();
            
            CallSpeaker rep = CallSpeaker.builder().tenantId(tenantId).call(call).speakerLabel("Speaker 1").speakerName("Sales Rep").role("REP").talkTimeSeconds(300).talkRatio(new BigDecimal("60.00")).build();
            speakerRepository.save(rep);

            CallTranscript utterance1 = CallTranscript.builder().tenantId(tenantId).call(call).speaker(rep).startTime(new BigDecimal("0.0")).endTime(new BigDecimal("5.0")).text("Real transcript generated by AI pipeline.").build();
            transcriptRepository.save(utterance1);

            CallInsight generalInsight = CallInsight.builder().tenantId(tenantId).call(call).insightType(InsightType.OBJECTION).category("Pricing").description("Budget too small").transcript(utterance1).build();
            insightRepository.save(generalInsight);

            CoachingRecommendation recommendation = CoachingRecommendation.builder().tenantId(tenantId).call(call).repId(call.getRepId()).category("Objection Handling").recommendation("AI generated recommendation.").playbookSuggestion("Pivot to value.").build();
            recommendationRepository.save(recommendation);

            ActionItem actionItem = ActionItem.builder().tenantId(tenantId).call(call).description("Extracted action item via AI.").status("PENDING").build();
            actionItemRepository.save(actionItem);

            SentimentAnalysis sentiment = SentimentAnalysis.builder().tenantId(tenantId).call(call).speaker(rep).overallScore(new BigDecimal("85.50")).build();
            sentimentAnalysisRepository.save(sentiment);

            call.setStatus(CallStatus.COMPLETED);
            call.setSummary("AI Generated Summary");
            callRepository.save(call);

            eventPublisher.publishEvent("call.analyzed", Map.of("callId", callId), tenantId);
            eventPublisher.publishEvent("action_item.extracted", Map.of("callId", callId, "actionItemId", actionItem.getId()), tenantId);

        } catch (Exception e) {
            Call call = callRepository.findByIdAndTenantId(callId, tenantId).orElse(null);
            if (call != null) {
                call.setStatus(CallStatus.FAILED);
                callRepository.save(call);
            }
        }
    }
}
