spring:
  datasource:
    url: jdbc:tc:postgresql:16:///wealthplan_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
