spring.application.name=billingai
server.port=8154

spring.datasource.url=jdbc:postgresql://localhost:5432/microsaas
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=billingai
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
