spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
