package com.microsaas.processminer.service;

import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.Map;
import java.util.List;
import java.math.BigDecimal;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class AIAnalysisService {
    
    private static final Logger log = LoggerFactory.getLogger(AIAnalysisService.class);

    private final RestTemplate restTemplate;
    private final String gatewayUrl;
    private final String apiKey;
    private final String model;
    private final ObjectMapper objectMapper;

    public AIAnalysisService(
            RestTemplate restTemplate,
            @Value("${cc.ai.gateway-url}") String gatewayUrl,
            @Value("${cc.ai.api-key}") String apiKey,
            @Value("${cc.ai.default-model}") String model,
            ObjectMapper objectMapper) {
        this.restTemplate = restTemplate;
        this.gatewayUrl = gatewayUrl;
        this.apiKey = apiKey;
        this.model = model;
        this.objectMapper = objectMapper;
    }

    public OpportunityScore analyzeOpportunity(String activityName, String processContext) {
        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.setBearerAuth(apiKey);

            String prompt = String.format(
                "Analyze the automation potential for the activity '%s' within the context of '%s'. " +
                "Return a JSON object with 'roi' (number 0 to 100), 'effort' (LOW, MEDIUM, HIGH), and 'rationale' (string).",
                activityName, processContext
            );

            Map<String, Object> requestBody = Map.of(
                "model", model,
                "messages", List.of(
                    Map.of("role", "system", "content", "You are an expert process automation analyst. Respond only with JSON."),
                    Map.of("role", "user", "content", prompt)
                ),
                "temperature", 0.2
            );

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);
            ResponseEntity<Map> response = restTemplate.postForEntity(gatewayUrl + "/v1/chat/completions", request, Map.class);
            
            // Parse response...
            Map<String, Object> body = response.getBody();
            if (body != null && body.containsKey("choices")) {
                List<Map<String, Object>> choices = (List<Map<String, Object>>) body.get("choices");
                if (!choices.isEmpty()) {
                    Map<String, Object> message = (Map<String, Object>) choices.get(0).get("message");
                    String content = (String) message.get("content");
                    
                    // Simple regex/parsing logic since LLM might wrap in ```json
                    if (content.startsWith("```json")) {
                        content = content.substring(7, content.length() - 3).trim();
                    }
                    
                    Map<String, Object> json = objectMapper.readValue(content, Map.class);
                    Number roi = (Number) json.getOrDefault("roi", 0);
                    String effort = (String) json.getOrDefault("effort", "MEDIUM");
                    String rationale = (String) json.getOrDefault("rationale", "Generated by AI");
                    
                    return new OpportunityScore(BigDecimal.valueOf(roi.doubleValue()), effort, rationale);
                }
            }
        } catch (Exception e) {
            log.warn("AI analysis failed, using fallback", e);
        }
        
        // Fallback
        return new OpportunityScore(new BigDecimal("15.5"), "MEDIUM", "Fallback analysis due to AI service unavailability.");
    }
    
    public record OpportunityScore(BigDecimal roi, String effort, String rationale) {}
}
