package com.crosscutting.starter.search;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Service;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;

@Service
public class SearchService {

    private static final Logger log = LoggerFactory.getLogger(SearchService.class);

    private final JdbcTemplate jdbcTemplate;

    private static final RowMapper<SearchResult> RESULT_ROW_MAPPER = (rs, rowNum) -> new SearchResult(
            rs.getString("resource_type"),
            UUID.fromString(rs.getString("resource_id")),
            rs.getString("content"),
            rs.getString("metadata"),
            rs.getDouble("score")
    );

    public SearchService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Upsert a document into the search index. The tsvector is auto-generated by the DB.
     */
    public void index(UUID tenantId, String resourceType, UUID resourceId, String content, String metadata) {
        String safeMetadata = (metadata != null) ? metadata : "{}";
        jdbcTemplate.update(
                """
                INSERT INTO cc.search_index (tenant_id, resource_type, resource_id, content, metadata, updated_at)
                VALUES (?, ?, ?, ?, ?::jsonb, NOW())
                ON CONFLICT (tenant_id, resource_type, resource_id)
                DO UPDATE SET content = EXCLUDED.content,
                              metadata = EXCLUDED.metadata,
                              updated_at = NOW()
                """,
                tenantId, resourceType, resourceId, content, safeMetadata
        );
    }

    /**
     * Full-text search using PostgreSQL tsvector/tsquery with ts_rank scoring.
     */
    public List<SearchResult> search(UUID tenantId, String query, String resourceType, int limit) {
        String sql;
        Object[] params;

        if (resourceType != null) {
            sql = """
                SELECT resource_type, resource_id, content, metadata::text AS metadata,
                       ts_rank(search_vector, plainto_tsquery('english', ?)) AS score
                FROM cc.search_index
                WHERE tenant_id = ?
                  AND resource_type = ?
                  AND search_vector @@ plainto_tsquery('english', ?)
                ORDER BY score DESC
                LIMIT ?
                """;
            params = new Object[]{query, tenantId, resourceType, query, limit};
        } else {
            sql = """
                SELECT resource_type, resource_id, content, metadata::text AS metadata,
                       ts_rank(search_vector, plainto_tsquery('english', ?)) AS score
                FROM cc.search_index
                WHERE tenant_id = ?
                  AND search_vector @@ plainto_tsquery('english', ?)
                ORDER BY score DESC
                LIMIT ?
                """;
            params = new Object[]{query, tenantId, query, limit};
        }

        return jdbcTemplate.query(sql, RESULT_ROW_MAPPER, params);
    }

    /**
     * Vector similarity search using cosine distance operator on the embeddings table.
     */
    public List<SearchResult> semanticSearch(UUID tenantId, double[] embedding, String resourceType, int limit) {
        String vectorLiteral = toVectorLiteral(embedding);
        String sql;
        Object[] params;

        if (resourceType != null) {
            sql = """
                SELECT e.resource_type, e.resource_id, s.content, s.metadata::text AS metadata,
                       1 - (e.embedding <=> ?::vector) AS score
                FROM cc.embeddings e
                LEFT JOIN cc.search_index s
                  ON s.tenant_id = e.tenant_id
                  AND s.resource_type = e.resource_type
                  AND s.resource_id = e.resource_id
                WHERE e.tenant_id = ?
                  AND e.resource_type = ?
                ORDER BY e.embedding <=> ?::vector
                LIMIT ?
                """;
            params = new Object[]{vectorLiteral, tenantId, resourceType, vectorLiteral, limit};
        } else {
            sql = """
                SELECT e.resource_type, e.resource_id, s.content, s.metadata::text AS metadata,
                       1 - (e.embedding <=> ?::vector) AS score
                FROM cc.embeddings e
                LEFT JOIN cc.search_index s
                  ON s.tenant_id = e.tenant_id
                  AND s.resource_type = e.resource_type
                  AND s.resource_id = e.resource_id
                WHERE e.tenant_id = ?
                ORDER BY e.embedding <=> ?::vector
                LIMIT ?
                """;
            params = new Object[]{vectorLiteral, tenantId, vectorLiteral, limit};
        }

        return jdbcTemplate.query(sql, RESULT_ROW_MAPPER, params);
    }

    /**
     * Hybrid search combining full-text and vector similarity with configurable weights.
     */
    public List<SearchResult> hybridSearch(UUID tenantId, String query, double[] embedding,
                                           double textWeight, double vectorWeight,
                                           String resourceType, int limit) {
        String vectorLiteral = toVectorLiteral(embedding);
        String sql;
        Object[] params;

        if (resourceType != null) {
            sql = """
                SELECT s.resource_type, s.resource_id, s.content, s.metadata::text AS metadata,
                       (? * ts_rank(s.search_vector, plainto_tsquery('english', ?))
                        + ? * (1 - (e.embedding <=> ?::vector))) AS score
                FROM cc.search_index s
                JOIN cc.embeddings e
                  ON e.tenant_id = s.tenant_id
                  AND e.resource_type = s.resource_type
                  AND e.resource_id = s.resource_id
                WHERE s.tenant_id = ?
                  AND s.resource_type = ?
                  AND s.search_vector @@ plainto_tsquery('english', ?)
                ORDER BY score DESC
                LIMIT ?
                """;
            params = new Object[]{textWeight, query, vectorWeight, vectorLiteral,
                    tenantId, resourceType, query, limit};
        } else {
            sql = """
                SELECT s.resource_type, s.resource_id, s.content, s.metadata::text AS metadata,
                       (? * ts_rank(s.search_vector, plainto_tsquery('english', ?))
                        + ? * (1 - (e.embedding <=> ?::vector))) AS score
                FROM cc.search_index s
                JOIN cc.embeddings e
                  ON e.tenant_id = s.tenant_id
                  AND e.resource_type = s.resource_type
                  AND e.resource_id = s.resource_id
                WHERE s.tenant_id = ?
                  AND s.search_vector @@ plainto_tsquery('english', ?)
                ORDER BY score DESC
                LIMIT ?
                """;
            params = new Object[]{textWeight, query, vectorWeight, vectorLiteral,
                    tenantId, query, limit};
        }

        return jdbcTemplate.query(sql, RESULT_ROW_MAPPER, params);
    }

    /**
     * Remove a document from the search index.
     */
    public void deleteIndex(UUID tenantId, String resourceType, UUID resourceId) {
        jdbcTemplate.update(
                "DELETE FROM cc.search_index WHERE tenant_id = ? AND resource_type = ? AND resource_id = ?",
                tenantId, resourceType, resourceId
        );
    }

    private String toVectorLiteral(double[] embedding) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < embedding.length; i++) {
            if (i > 0) sb.append(",");
            sb.append(embedding[i]);
        }
        sb.append("]");
        return sb.toString();
    }
}
